#!/bin/bash
#------------------------------------------------------------------------------
# Change these values!
source="/mnt/e/BKN-FIELD/Models/Paper1_2DwaveFlume/ModelRuns/LR_Domain/Scenarios/"
dest="/mnt/h/Models/Paper1_2DwaveFlume/ModelRuns/LR_Domain/Scenarios/"

# Script:
cd $source
for f in */; do #for all directories (*/) in $source...
	filename=$(basename "$f") #get the directory name 
	echo "Processing $f"
	if test -f "$dest$filename.zip"; then #check to see if the filename.zip exists in $dest
		echo "File already exists in destination! Skipping..."
	else
		echo "Writing $filename.zip"
		zip -qr "$dest${f%/}.zip" "$filename"
	fi
done
